name: Sync to Hugging Face hub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name mashrifmahim443
        git config --global user.email mahimhassan443@gmail.com

    - name: Pull latest changes
      run: |
        git pull origin main

    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git push https://huggingface.co/spaces/Mashrif/oxy main
